//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootieLegends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legend
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> CareerStartYear { get; set; }
        public Nullable<int> CareerEndYear { get; set; }
        public string Position { get; set; }
        public string Clubs { get; set; }
        public Nullable<int> Appearances { get; set; }
        public Nullable<int> Goals { get; set; }
        public Nullable<short> ClubHonors { get; set; }
        public Nullable<short> InternationalHonors { get; set; }
        public Nullable<short> BallondOrs { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
